---
- name: Configure nginx web server
  hosts: gcp
  tasks:
  - name: install nginx server
    apt:
      name: nginx
      state: latest
  - name: stop nginx server
    service:
      name: nginx
      state: started
